export const GOOGLE_CALENDAR_LINK = "https://calendar.app.google/antonioherrera";

export const SOCIAL_LINKS = {
  instagram: "https://www.instagram.com/antonioherrera.mundus?igsh=cjVuaGV0emVwYnp4&utm_source=qr",
  youtube: "https://youtube.com/@antonioherrera.mundus?si=12-Fng0GHvItSX2-",
  spotify: "https://open.spotify.com/artist/0oKlB9ESgXx9XMeqolUre6?si=brftvhePSoiH_-zHBn5YSA",
  boutique: "https://antonioherrera.shop/",
  mediaKit: "https://drive.google.com/drive/folders/17zF5Ly85M9FZqljwzYJHKgjZK63YD2zZ?usp=sharing",
  contactEmail: "contact@herrdesigncollective.com",
  collaborationEmail: "antonio.herrera@herrdesigncollective.com?subject=Collaboration%20Proposal",
};

export const CONTENT = {
  cta: "Schedule a Consultation", // Global CTA text
  heroTitle: "Design your life architecture.",
  heroSub: "Transform your life into a profound experience by building genuine connections.",
  musicHeroTitle: "Connect through music",
  musicHeroSub: "Transform your events into joyful experiences that build genuine connections.",
  showreelTitle: "Showreel",
  showreelSub: "Experience the rhythm, the light, and the pure energy of live connection.",
  partnersTitle: "Trusted by",
  heroCta: "Begin a new journey",
  banner1: "Visionary transformation that opens doors without pushing.",
  banner2: "Intentional expression woven into every object and act.",
  banner3: "Emotional resonance that lingers long after the moment ends.",
  promoTitle: "Life is too short to be stuck and miss the fun.",
  promoSub: "Problems are not fun. Don't let anything keep you back. You were designed for more.",
  promoCta: "Begin a new journey",
  featuresTitle: "Take control of your life journey.",
  featuresSub: "Have you ever experienced the following in your personal life...",
  feature1Title: "Identity.",
  feature1Desc: "Not knowing what you actually want — so you shape yourself around other people’s expectations and wonder why nothing feels right.",
  feature2Title: "Relationships.",
  feature2Desc: "Avoiding difficult conversations until resentment builds. The relationship doesn’t break from conflict — it breaks from silence.",
  feature3Title: "Work.",
  feature3Desc: "Confusing professional performance with personal worth. When the role defines the person, losing the role means losing yourself.",
  feature4Title: "Spaces.",
  feature4Desc: "Living or working in environments that were designed for a previous version of your life. The space keeps reinforcing who you were, not who you’re becoming.",
  feature5Title: "Leadership.",
  feature5Desc: "Leading through control rather than trust. It delivers short-term results but slowly empties the room of the people worth keeping.",
  expTitle: "I know how frustrating is to not move forward in life. I was there.",
  exp1: "More than 10 years of experience",
  exp2: "More than 50 engagements",
  exp3: "More than 20 countries visited",
  howTitle: "How to begin the new life journey",
  howStep1: "Click on Register",
  howStep2: "Fill out the form and hit Send",
  howStep3: "We will notify you if you are in",
  stopTitle: "Stop stressing about life. Connect, sing and dance with me.",
  stopText1: "You already know how to perform under pressure. You’ve mastered the serious side of life — the decisions, the discipline, the weight of getting it right. But when was the last time you let yourself be light?",
  stopText2: "Not distracted. Not numbing. Actually light — the kind where your body moves before your mind can object, where your voice joins in before you’ve decided whether you’re any good, where a room full of strangers becomes a room full of people you’d happily see again.\n\nJoy isn’t a reward for finishing your to-do list. It’s a practice. And like any practice, it gets easier the moment you stop performing and start participating. This is what I do. I create spaces where ambitious, intelligent people remember that connection, music, and movement aren’t extras. They’re the point. You don’t need to be good at it. You just need to show up willing.",
  continueReading: "Continue reading... >",
  registerNow: "Register now",
  pdfTitle: "5 ways to transform your life: Roadmap",
  pdfSub: "Download my free PDF and discover how your can enjoy your life more.",
  pdfCta: "Download PDF",
  unlockTitle: "Enjoy your life to the fullest.",
  footerShop: "Boutique",
  footerAbout: "About",
  footerBooking: "MANAGEMENT",
  footerCollections: "Collections",
  footerNewRoyal: "The New Royal",
  footerChangingEmotions: "Changing Emotions",
  footerSoftRoyal: "Soft Royal",
  footerStory: "Story",
  footerMediaKit: "Media Kit",
  footerContact: "Contact Management",
  footerBookConversation: "Propose collaboration",
  footerLanguages: "Languages",
  footerFollow: "Follow, Watch, Listen",
  tickerText: "Happy to serve you",
  testimonialsTitle: "Testimonials",
  test1Name: "Isabel A.",
  test1Role: "Brand Strategy Consultant",
  test1Quote: "You all are architects of unforgettable happy moments. Thank you for letting us celebrate with you. Great people in this group. I laughed and shouted and danced so much. My heart is so happy.",
  test2Name: "Toni-Ann O.",
  test2Role: "Photographer and Filmmaker",
  test2Quote: "Best event ever in life. Really an amazing night, dear. Thanks for being unapologetically authentic and for taking us on that journey with you.",
  test3Name: "Donika P.",
  test3Role: "Experience Designer",
  test3Quote: "Best. Party. Ever. I still can't believe it. It was like a magical dream. Thank you so much.",
  test4Name: "Clifford L.",
  test4Role: "Stylist and Image Consultant",
  test4Quote: "An unforgettable evening celebrating food, fashion, friendship and pure fabulousness. Surrounded by inspiring guests and the incredible creative team, we experienced a truly exclusive fusion of art and design. We had a ball.",
  test5Name: "Paulina Z.",
  test5Role: "Creative Technologist",
  test5Quote: "We absolutely adore you. The experience was so extraordinary that even my grandchildren won't believe I once attended a party like this. It was unforgettable in every sense.",
  test6Name: "Sarah O.",
  test6Role: "Lecturer",
  test6Quote: "I was so amazed by your performance. I was speechless afterwards. It was great. You are sooo talented. Thank you.",
  test7Name: "Stefan K.",
  test7Role: "Finance Executive",
  test7Quote: "I felt alive and people loved it.",
  test8Name: "Thiago Z.",
  test8Role: "Professional Services",
  test8Quote: "It was very professional, I will come again",
  test9Name: "Andreas S.",
  test9Role: "Entrepreneur, CIO & Family Office",
  test9Quote: "You are multi-skilled. I liked the combination of the talk, the design exhibition and the music performance. Thanks again for your event invitation. It was definitely a highlight of the year-end.",
  test10Name: "Isabel G.",
  test10Role: "Entrepreneur",
  test10Quote: "I know you organise innovative, creative events that step outside the ordinary. I love your work.",
  designTitle: "Under construction",
  designSubtitle: "I am designing a new life architecture space. Something extraordinary is being crafted.",
  designCta: "Join the VIP Waitlist",
  designEmailPlaceholder: "Enter your email address...",
  designNamePlaceholder: "Your elite name...",
  designSuccessText: "Thank you! You are on the registry for the next design evolution.",
  designBackCta: "Back to Home",
};
